### ISSUE TITLE
Has the link to the data changed?

### ISSUE THREAD

**Issue by maelle** [ropensci/riem#10]
@akrherz https://mesonet.agron.iastate.edu/cgi-bin/request/asos.py/ does not work today?

**Comment by akrherz** [comment]
Thanks to alerting me to this, for some reason the IPv4 HTTPS service was not functioning on my load balancer, I migrated to my backup system and it is back now.

**Comment by maelle** [comment]
Cool! Thanks! I'm happy it's working again :smile:
