### ISSUE TITLE
http issues riem_stations()

### ISSUE THREAD

**Issue by BenoitFayolle** [ropensci/riem#13]
Hi!
I get "Error in open.connection(con, "rb") : HTTP error 404." when trying to retreive the station list of a network with function riem_networks(). This error appeared 3 or 4 days ago. I never had the problem before.
Tried to update all my packages but I get the same error.
riem_measures() works fine when I manually choose the station name

platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          2.3                         
year           2015                        
month          12                          
day            10                          
svn rev        69752                       
language       R                           
version.string R version 3.2.3 (2015-12-10)
nickname       Wooden Christmas-Tree

**Comment by maelle** [comment]
Thanks I need to check this, it looks as if the site were down

**Comment by maelle** [comment]
@akrherz has the list of networks from http://mesonet.agron.iastate.edu/json/network.php?network= disappeared for good or just moved? Thanks in advance

**Comment by akrherz** [comment]
@maelle Hmmm, it should be network.py, but I am quasi confused as I thought network.php should have worked as well.  Will investigate and report back later.

**Comment by maelle** [comment]
Thanks!

**Comment by akrherz** [comment]
@maelle sorry for the delay, it is corrected now. Uffties :(

**Comment by maelle** [comment]
Thanks a lot @akrherz! 

@BenoitFayolle can I close this issue?

**Comment by BenoitFayolle** [comment]
All good, thanks!

**Comment by maelle** [comment]
Thanks again for notifying the issue @BenoitFayolle! 

Also, I'd be glad to hear about your use case for `riem`, but it's fine if you don't want to explain it to me. :-)
