### ISSUE TITLE
web access not working behind firewall

### ISSUE THREAD

**Issue by gregoryhunter** [ropensci/riem#15]
Hi there,

Is it possible to provide additional inputs for accessing IEM data over the internet? I am working behind a firewall that is blocking the request. 

`> riem_networks()`
`Error in open.connection(con, "rb") : HTTP error 403.`

`> riem_networks(station="CWJC")`
`Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: Connection timed out after 10015 milliseconds`

I can sometimes get connections to work depending on the exact method used to connect, but it doesn't appear that the functions take any arguments that would control this. Do I need to set something up beforehand to make this work?

**Comment by maelle** [comment]
@jeroen as a curl specialist do you have any idea what may work here? thanks :-)

**Comment by jeroen** [comment]
@gregoryhunter  can you please include the output for:

```r
sessionInfo()
ie_proxy_info()
curl::ie_get_proxy_for_url('http://mesonet.agron.iastate.edu')
```

**Comment by gregoryhunter** [comment]
Of course:


```
> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252   

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.2 tools_3.4.2   
```
```
> ie_proxy_info()
$AutoDetect
[1] FALSE

$AutoConfigUrl
NULL

$Proxy
[1] "webproxy.drdc-rddc.gc.ca:8080" 
$ProxyBypass 
[1] "localhost;127.0.0.1;*.drenet.dnd.ca;*.drdc-rddc.gc.ca;*.rddc-drdc.gc.ca;128.43.*;131.132.*;131.135.*;131.136.*;*.drdc.gc.ca;*.rddc.gc.ca;<local>" 
```
and finally:

```
> curl::ie_get_proxy_for_url('http://mesonet.agron.iastate.edu')
[1] "webproxy.drdc-rddc.gc.ca:8080"
```

Thank-you, by the way!

**Comment by jeroen** [comment]
Can you try this:

```
httr::config(proxy = "webproxy.drdc-rddc.gc.ca:8080")
```

And see if that changes anything?

**Comment by gregoryhunter** [comment]
No luck. Here is the output:

`> httr::config(proxy = "webproxy.drdc-rddc.gc.ca:8080")`
`<request>`
`Options:`
`* proxy: webproxy.drdc-rddc.gc.ca:8080`
`> riem_networks()`
`Error in open.connection(con, "rb") : HTTP error 403.`

**Comment by jeroen** [comment]
I'm sorry I forgot you need to call `set_config`:

```
httr::set_config(httr::config(proxy = "webproxy.drdc-rddc.gc.ca:8080"))
```

**Comment by gregoryhunter** [comment]
The result is the same: 403 error.

```r
> httr::set_config(httr::config(proxy = "webproxy.drdc-rddc.gc.ca:8080"))
> riem_networks()
Error in open.connection(con, "rb") : HTTP error 403.
```

**Comment by jeroen** [comment]
Hmmm can you try adding `http://` to the proxy server?

```r
httr::set_config(
  httr::config(proxy = "http://webproxy.drdc-rddc.gc.ca:8080", verbose = TRUE)
)
```

**Comment by gregoryhunter** [comment]
Still the same.

I should say that I AM able to access CRAN for package installation.

**Comment by jeroen** [comment]
Did you see any verbose output though?

**Comment by gregoryhunter** [comment]
No, it was the same as before. Here is the output:

`> httr::set_config(httr::config(proxy = "http://webproxy.drdc-rddc.gc.ca:8080", verbose = TRUE))`
`> riem_networks()`
`Error in open.connection(con, "rb") : HTTP error 403.`

**Comment by jeroen** [comment]
Ah okay I see it now. It errors in `open.connection` whereas which means it is not using `httr`. Try setting an environment variable instead:

```r
Sys.setenv(http_proxy = "webproxy.drdc-rddc.gc.ca:8080")
```
If that does not work also try setting this one:
```r
Sys.setenv(HTTPS_PROXY = "webproxy.drdc-rddc.gc.ca:8080")
```

**Comment by gregoryhunter** [comment]
Success! I set both of those, based on your email.

`> Sys.setenv(http_proxy = "webproxy.drdc-rddc.gc.ca:8080")`
`> Sys.setenv(HTTPS_PROXY = "webproxy.drdc-rddc.gc.ca:8080")`
`> riem_networks()`
`# A tibble: 267 x 2`
`       code                      name`
`      <chr>                     <chr>`
` 1 AE__ASOS United Arab Emirates ASOS`
` 2 AF__ASOS          Afghanistan ASOS`
` 3 AG__ASOS  Antigua and Barbuda ASOS`
` 4 AI__ASOS             Anguilla ASOS`
` 5  AK_ASOS               Alaska ASOS`
` 6  AL_ASOS              Alabama ASOS`
` 7 AL__ASOS              Albania ASOS`
` 8 AM__ASOS              Armenia ASOS`
` 9 AN__ASOS Netherlands Antilles ASOS`
`10 AO__ASOS               Angola ASOS`
`# ... with 257 more rows`

So as I suspected, the problem was on my end. Thank-you very much! I'm sure this will fix a bunch of other problems I have with spotty downloads in R. Will these settings stay set, or will I need to run a script on startup to set these every time?

**Comment by jeroen** [comment]
You should put them in a script in `~/.Rprofile`. See `?Startup`

**Comment by maelle** [comment]
Awesome and many thanks @jeroen! 😀

**Comment by gregoryhunter** [comment]
Done. Thanks so much @jeroen! I'm sorry for the trouble.

**Comment by gregoryhunter** [comment]
Done. Thanks so much @jeroen!
