### ISSUE TITLE
Invalid entries fetched by riem_measures()

### ISSUE THREAD

**Issue by tomekziel** [ropensci/riem#18]
In some cases downloaded data contains invalid lines. Example:

```
a <- riem_measures("LRAR", date_start = "2011-09-05", date_end="2011-09-06")
a[35:44,]

# A tibble: 10 x 24
   station valid                 lon   lat  tmpf  dwpf  ........  skyl4 wxcodes metar                     
   <chr>   <dttm>              <dbl> <dbl> <dbl> <dbl>  ........  <lgl> <chr>   <chr>                     
 1 LRAR    2011-09-05 18:00:00  21.4  46.1  78.8  57.2  ........  NA    NA      LRAR 051800Z 23004KT CAVO~
 2 LRAR    2011-09-05 18:30:00  21.4  46.1  78.8  59.0  ........  NA    NA      LRAR 051830Z 00000KT CAVO~
 3 LRAR    2011-09-05 19:00:00  21.4  46.1  77.0  59.0  ........  NA    NA      LRAR 051900Z 14004KT 110V~
 4 LRAR    2011-09-05 19:30:00  21.4  46.1  NA    NA    ........  NA    NA      LRAR 051930Z NIL          
 5 LRAR    2011-09-05 20:00:00  21.4  46.1  71.6  64.4  ........  NA    +SHRA   "LRAR 052000Z AUTO 25012K~
 6 Q1015   NA                   NA    NA    NA    NA    ........  NA    NA      NA                        
 7 LRAR    2011-09-05 20:30:00  21.4  46.1  NA    NA    ........  NA    NA      LRAR 052030Z NIL          
 8 LRAR    2011-09-05 21:00:00  21.4  46.1  69.8  66.2  ........  NA    SHRA    LRAR 052100Z AUTO 26012KT~
 9 LRAR    2011-09-05 22:00:00  21.4  46.1  68.0  64.4  ........  NA    -DZ     LRAR 052200Z AUTO VRB02KT~
10 LRAR    2011-09-05 23:00:00  21.4  46.1  68.0  66.2  ........  NA    -SHRA   LRAR 052300Z AUTO 15006KT~
> 
```
Please notice: a few columns were cut out for clarity. It looks like invalid line 6 (with all NA's but "station" column) happens after previous "metar" entry starts with a quote character in line 5 above

**Comment by maelle** [comment]
Thanks for the bug report!

@akrherz :wave:
1. thanks again for a great website and sorry to bother you!
2. in the website the data above corresponds to this URL https://mesonet.agron.iastate.edu/cgi-bin/request/asos.py?station=LRAR&data=all&year1=2011&month1=9&day1=5&year2=2011&month2=9&day2=6&tz=Etc%2FUTC&format=onlycomma&latlon=no&direct=no&report_type=1&report_type=2 The data has unexpected new lines. Is it because of the data source? Would it be possible to fix on your end?

**Comment by akrherz** [comment]
@maelle Yikes, that is not good.  I'll get this figured out once I get to work in about 2 hours.  Thanks for letting me know.

**Comment by maelle** [comment]
@akrherz  Thank *you* for being so responsive, and have a nice day!

**Comment by akrherz** [comment]
@maelle I have placed a band-aid on this issue to stop the bleeding, while later correct why it is getting inserted into my database with the `\n`.  Thanks for letting me know.

**Comment by maelle** [comment]
Ok, will let this issue open for now then. Thanks a ton for the quick fix!

@tomekziel please try again :-)

**Comment by tomekziel** [comment]
@maelle @akrherz You guys rock, quickest bugfix I've seen lately! I confirm bug is gone now, thanks!

**Comment by maelle** [comment]
Cool, I'll leave this open until @akrherz confirms he's happy with his fix.

**Comment by maelle** [comment]
@tomekziel If you have time, I'd be glad to hear about why and how you use the package, either in another issue or on our forum https://discuss.ropensci.org/c/usecases :-)

**Comment by akrherz** [comment]
@maelle sorry for the confusion, I would consider this issue fixed.

**Comment by maelle** [comment]
Aaah perfect then!
