### ISSUE TITLE
Upcoming IEM METAR/ASOS data service changes

### ISSUE THREAD

**Issue by akrherz** [ropensci/riem#22]
Hi, So I have a large code change in the hopper for push to the server and wanted to check with you folks first regarding the following changes, hopefully all non-breaking :)

New Columns
-------------------

code | meaning | units
--- | --- | ---
feel | Apparent Temperature (Wind Chill or Heat Index) | degF
ice_accretion_1hr | Ice Accretion over 1 Hour | inch
ice_accretion_3hr | Ice Accretion over 3 Hour | inch
ice_accretion_6hr | Ice Accretion over 6 Hour | inch
relh | Relative Humidity | % 

- `data=all` returns those additional columns above, note that the ice columns are not common among observation sites and only have a few years of history at sites that have the sensor.
- previously the header row of the CSV would have extraneous spaces between the column names, those are now removed
- a new CGI parameter `missing=value` is available which determines how null database values are handled.  The available options are `M`, `null`, or `empty`.  The current service would return `M`, which is the default.
- a new CGI parameter `trace=value` is available which determines how trace precipitation values are handled.  The available options are `T`, `null`, `empty` or `0.0001`.  The current service would return 0.0001, which is the default.
- general 2x speed up in response time, could be faster for some queries.
- backend service now allows 30 simultaneous requests, up from 10.

Again, I don't think and hope these changes break anything of yours, but wanted to get this issue opened to get feedback/concerns as I have not uploaded this change yet. :)

**Comment by maelle** [comment]
:wave: @akrherz, this sounds awesome! Will you deploy this directly at the current URL or will there be an URL for testing things first? I too don't think this will break the package, but we shall see, in any case very cool changes, congrats.

**Comment by akrherz** [comment]
Hi @maelle , sadly, my testing environment is not public at the moment.  Bad @akrherz.  The URL will not change and hopefully this all is transparent to end users!  I will let you know when this change goes in.

**Comment by maelle** [comment]
Ok no problem, thank you!

**Comment by akrherz** [comment]
Any loud explosions?  The change went in yesterday.

**Comment by maelle** [comment]
:wave: I've just relaunched checks of the package and they seem to all pass! :tada: I'll update the docs ASAP. Thanks again for the info!

**Comment by maelle** [comment]
I've updated docs and opened a separate issue for the implementation of new parameters. Thanks again!
