### ISSUE TITLE
Additional METAR/ASOS data fields

### ISSUE THREAD

**Issue by akrherz** [ropensci/riem#24]
I've added three additional fields as available for download from the METAR/ASOS data service.  These fields are:

 - peak_wind_gust :: Wind gust in knots from the METAR `PK WND` remark, this value may be different than the value found in the `gust` field.  The `gust` field is derived from the standard METAR wind report.
 - peak_wind_drct :: The wind direction in degrees North denoted in the METAR `PK WND` remark.
 - peak_wind_time :: The timestamp of the `PK WND` value in the same timezone as the `valid` field and controlled by the `tz` parameter.

This is now implemented and hopefully does not have side effects.

**Comment by maelle** [comment]
Thanks a lot! So much data!
