### ISSUE TITLE
Update to R 3.5.3 and/or 3.6.x branches

### ISSUE THREAD

**Issue by mpbeckman** [ropensci/riem#25]
Attempted installation of riem package from CRAN on both R 3.5.3 and 3.6.1, with error:

package ‘reim’ is not available (for R version 3.5.3)  

3.6.1 also gave same message with it's version.

Can this package be updated to support those versions (or at least the 3.6 branch) and pushed to CRAN?

Thanks.

**Comment by mpbeckman** [comment]
> reim

riem

**Comment by maelle** [comment]
This happens to me sometimes. To prevent such typos I sometimes usecthe RStudio interface to install packages because it has autocompletion. 🙂
