### ISSUE TITLE
riem_stations returns truncated station names for JP_ASOS

### ISSUE THREAD

**Issue by hidekoji** [ropensci/riem#29]
When I try `riem::riem_stations("JP__ASOS")` like below, It returns truncated station name like `ASAHIKAWA (JASDF` (Note: The parentheses are not closed. )

``` r
riem::riem_stations("JP__ASOS")
#> # A tibble: 111 x 4
#>    id    name                 lon   lat
#>    <chr> <chr>              <dbl> <dbl>
#>  1 RJOE  "AKENO (JASDF)   "  137.  34.5
#>  2 RJSK  "AKITA AIRPORT   "  140.  39.6
#>  3 RJKA  "AMAMI AIRPORT   "  130.  28.4
#>  4 RJSA  "AOMORI AIRPORT  "  141.  40.7
#>  5 RJEC  ASAHIKAWA AIRPOR    142.  43.7
#>  6 RJCA  ASAHIKAWA (JASDF    142.  43.8
#>  7 RJFA  "ASHIYA (JASDF)  "  131.  33.9
#>  8 RJTA  ATSUGI NAS (JMSD    139.  35.5
#>  9 RJAO  CHICHIJIMA ISLAN    142.  27.1
#> 10 RJCJ  "CHITOSE (JASDF) "  142.  42.8
#> # … with 101 more rows
```

<sup>Created on 2020-06-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

```r
> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reprex_0.3.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.2       rstudioapi_0.10  knitr_1.25       whisker_0.4      R6_2.4.0         rlang_0.4.0     
 [7] fansi_0.4.0      tools_3.6.0      xfun_0.10        utf8_1.1.4       cli_1.1.0        clipr_0.7.0     
[13] htmltools_0.4.0  assertthat_0.2.1 digest_0.6.21    tibble_2.1.3     crayon_1.3.4     processx_3.4.1  
[19] callr_3.3.2      vctrs_0.2.0      fs_1.3.1         ps_1.3.0         curl_4.2         zeallot_0.1.0   
[25] riem_0.1.1       evaluate_0.14    rmarkdown_1.16   compiler_3.6.0   pillar_1.4.2     backports_1.1.5 
[31] jsonlite_1.6     pkgconfig_2.0.3 
```

**Comment by maelle** [comment]
Thanks for the report.

I see the issue at the source too http://mesonet.agron.iastate.edu/json/network.php?network=JP__ASOS cc @akrherz

**Comment by akrherz** [comment]
Thanks, this is a truncation based on an old station table ingest into my database. :(  Presently, I think I only limit the names to 64 chars.  I'll see about fixing the names and updating this issue once complete.

**Comment by maelle** [comment]
Thanks a ton @akrherz!

**Comment by akrherz** [comment]
I merged in the names used by [jpatokal/openflights](https://github.com/jpatokal/openflights/blob/master/data).  Do things look better now?  It didn't cover all the IDs used, but most of them.

PS, I also have a script running now to backfill data for Japan prior to 2011.  It should be done later today.

**Comment by maelle** [comment]
thanks! In http://mesonet.agron.iastate.edu/json/network.php?network=JP__ASOS names like `[RJCA] ASAHIKAWA (JASDF` still look truncated to me?

**Comment by akrherz** [comment]
> still look truncated to me?

Indeed, the database I used " didn't cover all the IDs used".  I will look some more for a database that covers IDs like `RJCA`.

**Comment by akrherz** [comment]
Greetings,  I have merged in names found in a [station file](https://www1.ncdc.noaa.gov/pub/data/noaa/isd-history.txt) from NCEI now.  Better now?

**Comment by maelle** [comment]
I think so, thanks!

@hidekoji could you please have a look?

``` r
riem::riem_stations("JP__ASOS")
#> # A tibble: 111 x 4
#>    id    name                lon   lat
#>    <chr> <chr>             <dbl> <dbl>
#>  1 RJOE  Akeno              137.  34.5
#>  2 RJSK  Akita              140.  39.6
#>  3 RJKA  Amami              130.  28.4
#>  4 RJSA  Aomori             141.  40.7
#>  5 RJEC  Asahikawa          142.  43.7
#>  6 RJCA  ASAHIKAWA          142.  43.8
#>  7 RJFA  Ashiya             131.  33.9
#>  8 RJTA  Atsugi             139.  35.5
#>  9 RJAO  CHICHIJIMA ISLAND  142.  27.1
#> 10 RJCJ  Chitose            142.  42.8
#> # … with 101 more rows
```

<sup>Created on 2020-06-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hidekoji** [comment]
Thank you! It looks good to me know.
