### ISSUE TITLE
New asos.py service support for bulk download

### ISSUE THREAD

**Issue by akrherz** [ropensci/riem#31]
Greetings,

I have extended the `asos.py` service (ASOS / METAR data) to allow for bulk download of data from all stations I have.  The limits are that you have to specify a time period of `<= 24 hours`.  To enable this, you simply need not pass any `stations=` to the service.  Please let me know of any problems / concerns you have with this.

Additionally, I am going to create an `OpenAPI` service for this data soon, that may be more programatic to work with.  I will alert you to when it is ready for playing with.

**Comment by maelle** [comment]
Hello! Thanks, I'll hope I'll be able to look into this soon-ish then, that's exciting!

Or maybe a contributor might help, we shall see.

Thanks for the info about OpenAPI too!

**Comment by maelle** [comment]
So, at last I have experimented with the bulk download. I was wondering whether it'd be possible to bulk-download by network to make the resulting data a bit smaller depending on the needs.

Also, at the moment, one can only query by date, not by hour, so if I follow correctly to use the bulk download one needs to use the same end and start dates?

An alternative to making the bulk download available in the same format as normal queries would be to use the strategy of the CRAN checks API, where one gets a link to an Amazon S3 file https://docs.cranchecks.info/#history

**Comment by akrherz** [comment]
Thanks for the feedback:

> I was wondering whether it'd be possible to bulk-download by network to make the resulting data a bit smaller depending on the needs.

OK, if one specifies the `network=` parameter, it will query only stations within that IEM network.

> Also, at the moment, one can only query by date, not by hour, so if I follow correctly to use the bulk download one needs to use the same end and start dates?

Oh dear, that's sub-optimal.  Indeed, that is how it works currently.

**Comment by maelle** [comment]
@akrherz where can I read the latest news on bulk download? Thank you!

**Comment by akrherz** [comment]
> @akrherz where can I read the latest news on bulk download? Thank you!

Sorry, I don't have any place that announces changes like this.  

So, looking at this issue.  I can't figure out what I was going to do :(

**Comment by maelle** [comment]
No problem, I'll close it! Thank you!
