### ISSUE TITLE
what does the sky coverage output means?

### ISSUE THREAD

**Issue by maelle** [ropensci/riem#7]
@akrherz is there a dictionary somewhere for these variables?

**Comment by akrherz** [comment]
The conversion of these text labels to an actual numeric value is somewhat problematic.  The general names of each are:

| code | label |
| --- | --- |
| CLR | Clear Skies (up to the altitude that the sensor can sense clouds) |
| FEW | Few |
| SCT | Scattered |
| BKN | Broken Cloud Deck |
| OVC | Overcast |
| /// | Missing |
| VV | (I am unsure) |
| NSC | (I am unsure) |
| NCD | (I am unsure) |

**Comment by maelle** [comment]
thanks! do you know whether the codes are consistent throughout stations/networks?

**Comment by akrherz** [comment]
@masalmon The codes are consistent, but their translation into numeric values will be tricky based on the exact type of sensor / platform involved.  This varies even within an individual network.

**Comment by maelle** [comment]
@akrherz ok thanks this makes sense
